# -*- coding: utf-8 -*-
"""GRU_Best_Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/104irxlWkp63ZF5IVSSUotwhTbWfnHaHC
"""

# ============================================================================
# GRU MODEL - Best Model from Hyperparameter Optimization
# Optimized hyperparameters: hidden_size=128, num_layers=1, lr=0.00194, batch_size=32
# Uses same data pipeline as LTC notebook for direct comparison
# ============================================================================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
from google.colab import files
import io
import time

# ============================================================================
# 1. LOAD AND NORMALIZE DATA (identical to LTC notebook)
# ============================================================================
print("=" * 70)
print("DATA LOADING & NORMALIZATION")
print("=" * 70)

uploaded = files.upload()
filename = list(uploaded.keys())[0]
df = pd.read_excel(io.BytesIO(uploaded[filename]))
df['date'] = pd.to_datetime(df['date'])

# Store original range for denormalization
conc_min = df['Concentration'].min()
conc_max = df['Concentration'].max()

# Normalize concentration to [0, 1]
df['Concentration_norm'] = (df['Concentration'] - conc_min) / (conc_max - conc_min)

print(f"Dataset: {len(df)} samples")
print(f"Concentration range: [{conc_min:.2f}, {conc_max:.2f}] ppm")
print(f"Normalized to [0, 1]")

# ============================================================================
# 2. CREATE SEQUENCES (1-step ahead, seq_length=50)
# ============================================================================
seq_length = 50

sequences, targets = [], []
for i in range(len(df) - seq_length):
    sequences.append(df['Concentration_norm'].iloc[i:i+seq_length].values)
    targets.append(df['Concentration_norm'].iloc[i+seq_length])

X = np.array(sequences, dtype=np.float32).reshape(-1, seq_length, 1)
y = np.array(targets, dtype=np.float32).reshape(-1, 1)

# Train/test split (80/20, chronological)
split_idx = int(0.8 * len(X))
train_x, test_x = X[:split_idx], X[split_idx:]
train_y, test_y = y[:split_idx], y[split_idx:]

print(f"\nSequence length: {seq_length}, Prediction: 1-step ahead")
print(f"Train: {len(train_x)} samples, Test: {len(test_x)} samples")

# ============================================================================
# 3. GRU MODEL DEFINITION
# ============================================================================
class GRUModel(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers, output_size):
        super(GRUModel, self).__init__()
        self.gru = nn.GRU(input_size, hidden_size, num_layers, batch_first=True)
        self.fc = nn.Linear(hidden_size, output_size)

    def forward(self, x):
        out, _ = self.gru(x)
        out = self.fc(out[:, -1, :])
        return out

# ============================================================================
# 4. TRAINING (best hyperparameters from Optuna optimization)
# ============================================================================
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"\nDevice: {device}")
if device.type == 'cuda':
    print(f"GPU: {torch.cuda.get_device_name(0)}")

# Best hyperparameters from optimization
HIDDEN_SIZE = 128
NUM_LAYERS = 1
LEARNING_RATE = 0.0019355062390914162
BATCH_SIZE = 32
EPOCHS = 100

# Create dataloaders
train_dataset = TensorDataset(torch.FloatTensor(train_x), torch.FloatTensor(train_y))
test_dataset = TensorDataset(torch.FloatTensor(test_x), torch.FloatTensor(test_y))
train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False)

# Initialize model
model = GRUModel(input_size=1, hidden_size=HIDDEN_SIZE, num_layers=NUM_LAYERS, output_size=1).to(device)
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=LEARNING_RATE)

print(f"\nModel: GRU (hidden={HIDDEN_SIZE}, layers={NUM_LAYERS})")
print(f"Parameters: {sum(p.numel() for p in model.parameters()):,}")
print(f"Training for {EPOCHS} epochs...\n")

# Training loop
train_losses = []
start_time = time.time()

for epoch in range(EPOCHS):
    model.train()
    epoch_loss = 0
    for X_batch, y_batch in train_loader:
        X_batch, y_batch = X_batch.to(device), y_batch.to(device)
        optimizer.zero_grad()
        outputs = model(X_batch)
        loss = criterion(outputs, y_batch)
        loss.backward()
        optimizer.step()
        epoch_loss += loss.item()

    avg_loss = epoch_loss / len(train_loader)
    train_losses.append(avg_loss)

    if (epoch + 1) % 10 == 0:
        print(f"  Epoch {epoch+1:3d}/{EPOCHS} | Train Loss: {avg_loss:.6f}")

training_time = time.time() - start_time
print(f"\nTraining time: {training_time:.2f} seconds")

# ============================================================================
# 5. EVALUATION
# ============================================================================
model.eval()
all_preds, all_targets = [], []

start_time = time.time()
with torch.no_grad():
    for X_batch, y_batch in test_loader:
        X_batch = X_batch.to(device)
        preds = model(X_batch)
        all_preds.append(preds.cpu().numpy())
        all_targets.append(y_batch.numpy())
inference_time = time.time() - start_time

predictions = np.concatenate(all_preds).flatten()
actuals = np.concatenate(all_targets).flatten()

# Denormalize to ppm
predictions_ppm = predictions * (conc_max - conc_min) + conc_min
actuals_ppm = actuals * (conc_max - conc_min) + conc_min

# Metrics
mse_norm = mean_squared_error(actuals, predictions)
rmse_norm = np.sqrt(mse_norm)
rmse_ppm = np.sqrt(mean_squared_error(actuals_ppm, predictions_ppm))
mae_ppm = mean_absolute_error(actuals_ppm, predictions_ppm)
r2 = r2_score(actuals, predictions)

print("\n" + "=" * 70)
print("GRU MODEL PERFORMANCE")
print("=" * 70)
print(f"  MSE (normalized):   {mse_norm:.6f}")
print(f"  RMSE (normalized):  {rmse_norm:.6f}")
print(f"  RMSE (ppm):         {rmse_ppm:.2f} ppm")
print(f"  MAE (ppm):          {mae_ppm:.2f} ppm")
print(f"  R²:                 {r2:.4f}")
print(f"  Training time:      {training_time:.2f} s")
print(f"  Inference time:     {inference_time:.4f} s")
print("=" * 70)

# ============================================================================
# 6. PUBLICATION-QUALITY PLOTS
# ============================================================================

# --- Plot style setup ---
plt.rcParams.update({
    'font.size': 12,
    'font.family': 'serif',
    'axes.linewidth': 1.2,
    'xtick.major.width': 1.0,
    'ytick.major.width': 1.0,
    'figure.dpi': 150,
})

COLOR_ACTUAL = '#2166AC'     # Dark blue
COLOR_PRED = '#D6604D'       # Muted red
COLOR_SCATTER = '#4393C3'    # Medium blue
COLOR_PERFECT = '#1A1A1A'    # Near black
COLOR_LOSS = '#B2182B'       # Dark red

# --- Figure 1: Training Loss ---
fig, ax = plt.subplots(figsize=(8, 5))
ax.plot(range(1, EPOCHS+1), train_losses, color=COLOR_LOSS, linewidth=1.5)
ax.set_xlabel('Epoch', fontsize=13, fontweight='bold')
ax.set_ylabel('Mean Squared Error (MSE)', fontsize=13, fontweight='bold')
ax.set_title('GRU Model Training Loss', fontsize=14, fontweight='bold')
ax.grid(True, alpha=0.3, linestyle='--')
ax.set_xlim(1, EPOCHS)
ax.tick_params(axis='both', labelsize=11)
plt.tight_layout()
plt.savefig('gru_training_loss.png', dpi=300, bbox_inches='tight')
plt.show()

# --- Figure 2: Predictions vs Actual (full test set, normalized) ---
fig, ax = plt.subplots(figsize=(14, 5))
ax.plot(actuals, label='Actual', color=COLOR_ACTUAL, linewidth=0.8, alpha=0.85)
ax.plot(predictions, label='Predicted', color=COLOR_PRED, linewidth=0.8, alpha=0.85)
ax.set_xlabel('Sample Index', fontsize=13, fontweight='bold')
ax.set_ylabel('Normalized Methane Concentration', fontsize=13, fontweight='bold')
ax.set_title('GRU Model: Predicted vs Actual Methane Concentration', fontsize=14, fontweight='bold')
ax.legend(fontsize=12, loc='upper right', framealpha=0.9, edgecolor='gray')
ax.grid(True, alpha=0.3, linestyle='--')
ax.set_xlim(0, len(actuals))
ax.set_ylim(-0.02, max(actuals.max(), predictions.max()) * 1.1)
ax.tick_params(axis='both', labelsize=11)
plt.tight_layout()
plt.savefig('gru_predictions_vs_actual.png', dpi=300, bbox_inches='tight')
plt.show()

# --- Figure 3: Predictions vs Actual (ppm scale) ---
fig, ax = plt.subplots(figsize=(14, 5))
ax.plot(actuals_ppm, label='Actual', color=COLOR_ACTUAL, linewidth=0.8, alpha=0.85)
ax.plot(predictions_ppm, label='Predicted', color=COLOR_PRED, linewidth=0.8, alpha=0.85)
ax.set_xlabel('Sample Index', fontsize=13, fontweight='bold')
ax.set_ylabel('Methane Concentration (ppm)', fontsize=13, fontweight='bold')
ax.set_title('GRU Model: Predicted vs Actual Methane Concentration', fontsize=14, fontweight='bold')
ax.legend(fontsize=12, loc='upper right', framealpha=0.9, edgecolor='gray')
ax.grid(True, alpha=0.3, linestyle='--')
ax.set_xlim(0, len(actuals_ppm))
ax.tick_params(axis='both', labelsize=11)
plt.tight_layout()
plt.savefig('gru_predictions_vs_actual_ppm.png', dpi=300, bbox_inches='tight')
plt.show()

# --- Figure 4: Scatter Plot (True vs Predicted, normalized) ---
fig, ax = plt.subplots(figsize=(7, 7))
ax.scatter(actuals, predictions, alpha=0.3, s=12, color=COLOR_SCATTER, edgecolors='none', label='Predictions')
lim_min = min(actuals.min(), predictions.min()) - 0.02
lim_max = max(actuals.max(), predictions.max()) + 0.02
ax.plot([lim_min, lim_max], [lim_min, lim_max], '--', color=COLOR_PERFECT, linewidth=1.5, label='Perfect Prediction')
ax.set_xlabel('Actual (Normalized Concentration)', fontsize=13, fontweight='bold')
ax.set_ylabel('Predicted (Normalized Concentration)', fontsize=13, fontweight='bold')
ax.set_title(f'GRU Model: Predicted vs Actual\nR² = {r2:.4f}, RMSE = {rmse_ppm:.2f} ppm', fontsize=14, fontweight='bold')
ax.legend(fontsize=11, loc='upper left', framealpha=0.9, edgecolor='gray')
ax.set_xlim(lim_min, lim_max)
ax.set_ylim(lim_min, lim_max)
ax.set_aspect('equal')
ax.grid(True, alpha=0.3, linestyle='--')
ax.tick_params(axis='both', labelsize=11)
plt.tight_layout()
plt.savefig('gru_scatter_plot.png', dpi=300, bbox_inches='tight')
plt.show()

# Download all plots
for fname in ['gru_training_loss.png', 'gru_predictions_vs_actual.png',
              'gru_predictions_vs_actual_ppm.png', 'gru_scatter_plot.png',
              'gru_spike_detail.png', 'gru_residual_analysis.png']:
    files.download(fname)

