# -*- coding: utf-8 -*-
"""LTC_Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_LTcjxGjGNpHf-LUOTncclOitLRzKssL
"""

# ============================================================================
# INSTALL DEPENDENCIES (restart runtime after this cell)
# ============================================================================
!pip uninstall -y jax jaxlib 2>/dev/null
!pip install ml_dtypes==0.5.0
!pip install tensorflow==2.17.0
!pip install ncps==0.0.7
!pip install openpyxl

print("Installation complete. Now restart runtime: Runtime → Restart runtime")
print("After restart, continue from the next cell.")

# ============================================================================
# LTC MODEL - Liquid Time-Constant Neural Network
# Architecture: Dense(24, tanh) → LTC(AutoNCP(24,1))
# Uses same data pipeline and plots as GRU notebook for direct comparison
# ============================================================================

import os
os.environ['TF_USE_LEGACY_KERAS'] = '1'

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from ncps import wirings
from ncps.tf import LTC
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
from google.colab import files
import io
import time

print(f"TensorFlow version: {tf.__version__}")

# ============================================================================
# 1. LOAD AND NORMALIZE DATA (identical to GRU notebook)
# ============================================================================
print("=" * 70)
print("DATA LOADING & NORMALIZATION")
print("=" * 70)

uploaded = files.upload()
filename = list(uploaded.keys())[0]
df = pd.read_excel(io.BytesIO(uploaded[filename]))
df['date'] = pd.to_datetime(df['date'])

# Store original range for denormalization
conc_min = df['Concentration'].min()
conc_max = df['Concentration'].max()

# Normalize concentration to [0, 1]
df['Concentration'] = (df['Concentration'] - conc_min) / (conc_max - conc_min)

# Calculate elapsed time in seconds
df['elapsed_time'] = df['date'].diff().dt.total_seconds().fillna(0).astype(np.float32)

print(f"Dataset: {len(df)} samples")
print(f"Concentration range: [{conc_min:.2f}, {conc_max:.2f}] ppm")
print(f"Normalized to [0, 1]")

# ============================================================================
# 2. CREATE SEQUENCES (1-step ahead, seq_length=50)
# ============================================================================
seq_length = 50

sequences, elapsed_times, targets = [], [], []
for i in range(len(df) - seq_length):
    sequences.append(df['Concentration'].iloc[i:i+seq_length].values)
    elapsed_times.append(df['elapsed_time'].iloc[i:i+seq_length].values)
    targets.append(df['Concentration'].iloc[i+seq_length])

X = np.array(sequences, dtype=np.float32).reshape(-1, seq_length, 1)
T = np.array(elapsed_times, dtype=np.float32).reshape(-1, seq_length, 1)
y = np.array(targets, dtype=np.float32).reshape(-1, 1)

# Replace zeros in timespans with small positive value (LTC requirement)
T = np.where(T == 0, 0.001, T)

# Train/test split (80/20, chronological)
split_idx = int(0.8 * len(X))
train_x, test_x = X[:split_idx], X[split_idx:]
train_t, test_t = T[:split_idx], T[split_idx:]
train_y, test_y = y[:split_idx], y[split_idx:]

print(f"\nSequence length: {seq_length}, Prediction: 1-step ahead")
print(f"Train: {len(train_x)} samples, Test: {len(test_x)} samples")
print(f"Elapsed time range: [{T.min():.4f}, {T.max():.2f}] seconds")

# ============================================================================
# 3. BUILD LTC MODEL
# ============================================================================
tf.keras.backend.clear_session()

fc_wiring = wirings.AutoNCP(24, 1)  # 24 hidden units, 1 motor neuron
input_values = keras.Input(shape=(None, 1))
input_time = keras.Input(shape=(None, 1))

dense_layer = keras.layers.Dense(24, activation='tanh')
ltc_layer = LTC(fc_wiring, return_sequences=False)

x = dense_layer(input_values)
x = ltc_layer((x, input_time))

model = keras.Model(inputs=(input_values, input_time), outputs=x)
model.compile(optimizer=keras.optimizers.Adam(0.0001), loss='mean_squared_error')
model.summary()

# ============================================================================
# 4. TRAINING
# ============================================================================
EPOCHS = 100
BATCH_SIZE = 32

print(f"\nModel: LTC (AutoNCP wiring, 24 units, 1 motor neuron)")
print(f"Training for {EPOCHS} epochs...\n")

start_time = time.time()
history = model.fit(
    x=(train_x, train_t),
    y=train_y,
    batch_size=BATCH_SIZE,
    epochs=EPOCHS,
    verbose=1
)
training_time = time.time() - start_time
print(f"\nTraining time: {training_time:.2f} seconds")

# ============================================================================
# 5. EVALUATION
# ============================================================================
test_loss = model.evaluate(x=(test_x, test_t), y=test_y, verbose=0)

start_time = time.time()
predictions = model.predict(x=(test_x, test_t), verbose=0).flatten()
inference_time = time.time() - start_time

actuals = test_y.flatten()

# Denormalize to ppm
predictions_ppm = predictions * (conc_max - conc_min) + conc_min
actuals_ppm = actuals * (conc_max - conc_min) + conc_min

# Metrics
mse_norm = mean_squared_error(actuals, predictions)
rmse_norm = np.sqrt(mse_norm)
rmse_ppm = np.sqrt(mean_squared_error(actuals_ppm, predictions_ppm))
mae_ppm = mean_absolute_error(actuals_ppm, predictions_ppm)
r2 = r2_score(actuals, predictions)

print("\n" + "=" * 70)
print("LTC MODEL PERFORMANCE")
print("=" * 70)
print(f"  MSE (normalized):   {mse_norm:.6f}")
print(f"  RMSE (normalized):  {rmse_norm:.6f}")
print(f"  RMSE (ppm):         {rmse_ppm:.2f} ppm")
print(f"  MAE (ppm):          {mae_ppm:.2f} ppm")
print(f"  R²:                 {r2:.4f}")
print(f"  Training time:      {training_time:.2f} s")
print(f"  Inference time:     {inference_time:.4f} s")
print("=" * 70)

# ============================================================================
# 6. PUBLICATION-QUALITY PLOTS
# ============================================================================

# --- Plot style setup ---
plt.rcParams.update({
    'font.size': 12,
    'font.family': 'serif',
    'axes.linewidth': 1.2,
    'xtick.major.width': 1.0,
    'ytick.major.width': 1.0,
    'figure.dpi': 150,
})

COLOR_ACTUAL = '#2166AC'     # Dark blue
COLOR_PRED = '#D6604D'       # Muted red
COLOR_SCATTER = '#4393C3'    # Medium blue
COLOR_PERFECT = '#1A1A1A'    # Near black
COLOR_LOSS = '#B2182B'       # Dark red

# --- Figure 1: Training Loss ---
fig, ax = plt.subplots(figsize=(8, 5))
ax.plot(range(1, EPOCHS+1), history.history['loss'], color=COLOR_LOSS, linewidth=1.5)
ax.set_xlabel('Epoch', fontsize=13, fontweight='bold')
ax.set_ylabel('Mean Squared Error (MSE)', fontsize=13, fontweight='bold')
ax.set_title('LTC Model Training Loss', fontsize=14, fontweight='bold')
ax.grid(True, alpha=0.3, linestyle='--')
ax.set_xlim(1, EPOCHS)
ax.tick_params(axis='both', labelsize=11)
plt.tight_layout()
plt.savefig('ltc_training_loss.png', dpi=300, bbox_inches='tight')
plt.show()

# --- Figure 2: Predictions vs Actual (full test set, normalized) ---
fig, ax = plt.subplots(figsize=(14, 5))
ax.plot(actuals, label='Actual', color=COLOR_ACTUAL, linewidth=0.8, alpha=0.85)
ax.plot(predictions, label='Predicted', color=COLOR_PRED, linewidth=0.8, alpha=0.85)
ax.set_xlabel('Sample Index', fontsize=13, fontweight='bold')
ax.set_ylabel('Normalized Methane Concentration', fontsize=13, fontweight='bold')
ax.set_title('LTC Model: Predicted vs Actual Methane Concentration', fontsize=14, fontweight='bold')
ax.legend(fontsize=12, loc='upper right', framealpha=0.9, edgecolor='gray')
ax.grid(True, alpha=0.3, linestyle='--')
ax.set_xlim(0, len(actuals))
ax.set_ylim(-0.02, max(actuals.max(), predictions.max()) * 1.1)
ax.tick_params(axis='both', labelsize=11)
plt.tight_layout()
plt.savefig('ltc_predictions_vs_actual.png', dpi=300, bbox_inches='tight')
plt.show()

# --- Figure 3: Predictions vs Actual (ppm scale) ---
fig, ax = plt.subplots(figsize=(14, 5))
ax.plot(actuals_ppm, label='Actual', color=COLOR_ACTUAL, linewidth=0.8, alpha=0.85)
ax.plot(predictions_ppm, label='Predicted', color=COLOR_PRED, linewidth=0.8, alpha=0.85)
ax.set_xlabel('Sample Index', fontsize=13, fontweight='bold')
ax.set_ylabel('Methane Concentration (ppm)', fontsize=13, fontweight='bold')
ax.set_title('LTC Model: Predicted vs Actual Methane Concentration', fontsize=14, fontweight='bold')
ax.legend(fontsize=12, loc='upper right', framealpha=0.9, edgecolor='gray')
ax.grid(True, alpha=0.3, linestyle='--')
ax.set_xlim(0, len(actuals_ppm))
ax.tick_params(axis='both', labelsize=11)
plt.tight_layout()
plt.savefig('ltc_predictions_vs_actual_ppm.png', dpi=300, bbox_inches='tight')
plt.show()

# --- Figure 4: Scatter Plot (True vs Predicted, normalized) ---
fig, ax = plt.subplots(figsize=(7, 7))
ax.scatter(actuals, predictions, alpha=0.3, s=12, color=COLOR_SCATTER, edgecolors='none', label='Predictions')
lim_min = min(actuals.min(), predictions.min()) - 0.02
lim_max = max(actuals.max(), predictions.max()) + 0.02
ax.plot([lim_min, lim_max], [lim_min, lim_max], '--', color=COLOR_PERFECT, linewidth=1.5, label='Perfect Prediction')
ax.set_xlabel('Actual (Normalized Concentration)', fontsize=13, fontweight='bold')
ax.set_ylabel('Predicted (Normalized Concentration)', fontsize=13, fontweight='bold')
ax.set_title(f'LTC Model: Predicted vs Actual\nR² = {r2:.4f}, RMSE = {rmse_ppm:.2f} ppm', fontsize=14, fontweight='bold')
ax.legend(fontsize=11, loc='upper left', framealpha=0.9, edgecolor='gray')
ax.set_xlim(lim_min, lim_max)
ax.set_ylim(lim_min, lim_max)
ax.set_aspect('equal')
ax.grid(True, alpha=0.3, linestyle='--')
ax.tick_params(axis='both', labelsize=11)
plt.tight_layout()
plt.savefig('ltc_scatter_plot.png', dpi=300, bbox_inches='tight')
plt.show()
plt.tight_layout()
plt.savefig('ltc_residual_analysis.png', dpi=300, bbox_inches='tight')
plt.show()

print("\n" + "=" * 70)
print("All plots saved as PNG files (300 DPI)")
print("=" * 70)

# Download all plots
for fname in ['ltc_training_loss.png', 'ltc_predictions_vs_actual.png',
              'ltc_predictions_vs_actual_ppm.png', 'ltc_scatter_plot.png',
              'ltc_spike_detail.png', 'ltc_residual_analysis.png']:
    files.download(fname)